# Generated by Django 3.1.2 on 2021-05-31 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item_img',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='resume',
        ),
    ]
