# Generated by Django 3.1.2 on 2020-11-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_img',
            field=models.FileField(upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner_id',
            field=models.IntegerField(default=0),
        ),
    ]
