# Generated by Django 3.1.1 on 2020-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200923_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_price',
            field=models.FloatField(default=1),
        ),
    ]
