# Generated by Django 3.1.1 on 2020-09-26 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200924_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
