# Generated by Django 3.1.1 on 2020-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
