# Generated by Django 3.1.1 on 2020-09-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='username',
        ),
    ]
