# Generated by Django 3.1.1 on 2020-09-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200929_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales',
            new_name='sale',
        ),
    ]
