# Generated by Django 3.1.1 on 2020-09-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200929_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='seller_id',
        ),
    ]
