# Generated by Django 3.1.1 on 2020-10-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200930_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner_id',
            field=models.IntegerField(default=0),
        ),
    ]
